# Generated by Django 4.2.16 on 2026-06-07 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('call_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='workspace.channel')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zc_calls',
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participants', to='calls.call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zc_call_participants',
                'unique_together': {('call', 'user')},
            },
        ),
        migrations.AddField(
            model_name='call',
            name='participants',
            field=models.ManyToManyField(related_name='calls', through='calls.CallParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
